# createArticle
POST {{url}}/articles
Authorization: {{token0}}
Content-Type: application/json
{
  "article": {
    "title": "asd",
    "description": "this is a description",
    "body": "this is a body",
    "tagList": ["some", "random", "tags"]
  }
}

# deleteArticle
DELETE {{url}}/articles/short
Authorization: {{token0}}

# favoriteArticle
POST {{url}}/articles/short/favorite
Authorization: {{token0}}

# unfavoriteArticle
DELETE {{url}}/articles/short/favorite
Authorization: {{token0}}

# getArticleWithSlug
GET {{url}}/articles/short
# Authorization: {{token1}}

# updateArticle
PUT {{url}}/articles/short
Authorization: {{token0}}
Content-Type: application/json
{
  "article": {
    "title": "asd",
    "description": "short updated",
    "body": "short updated",
    "tagList": ["bruh"]
  }
}

# listArticles with queries
GET {{url}}/articles
# Authorization: {{token0}}

# offset
GET {{url}}/articles?offset=5
Authorization: {{token0}}

# limit
GET {{url}}/articles?limit=5
Authorization: {{token0}}

# tag
GET {{url}}/articles?tag=ciminatio
Authorization: {{token0}}

# favoriter
GET {{url}}/articles?favorited-userid=6683fefece1724ef4ae49c18
Authorization: {{token0}}
