# createArticle
POST {{url}}/articles
Authorization: {{token0}}
Content-Type: application/json
{
  "article": {
    "title": "short", 
    "description": "this is a description", 
    "body": "this is a body", 
    "tagList": ["some", "random", "tags"]
  }
}

# deleteArticle
DELETE {{url}}/articles/short
Authorization: {{token0}}

# favoriteArticle
POST {{url}}/articles/short/favorite
Authorization: {{token0}}

# unfavoriteArticle
DELETE {{url}}/articles/short/favorite
Authorization: {{token0}}

# getArticleWithSlug
GET {{url}}/articles/short
# Authorization: {{token1}}

# updateArticle
PUT {{url}}/articles/short
Authorization: {{token0}}
Content-Type: application/json
{
  "article": {
    "title": "short", 
    "description": "short updated", 
    "body": "short updated", 
    "tagList": ["bruh"]
  }
}

# listArticles with queries
GET {{url}}/articles
# Authorization: {{token0}}

GET {{url}}/articles?offset=5 # offset
Authorization: {{token0}}

GET {{url}}/articles?limit=5& # limit
Authorization: {{token0}}

GET {{url}}/articles?tag=ad # tag
Authorization: {{token0}}

GET {{url}}/articles?favorited=minhhoccode111 # favoriter
Authorization: {{token0}}
