# addCommentsToArticle,
POST {{url}}/articles/asd1-0/comments
Authorization: {{token1}}
Content-Type: application/json
{
  "comment": {
    "body": "contact"
  }
}


# getCommentsFromArticle,
GET {{url}}/articles/asd1-0/comments
Authorization: {{token1}}


# deleteComment,
DELETE {{url}}/articles/asd1-0/comments/665445db1d9d0635c1ddc54e
Authorization: {{token1}}
