# addCommentsToArticle,
POST {{url}}/articles/short/comments
Authorization: {{token0}}
Content-Type: application/json
{
  "comment": {
    "body": "third comment"
  }
}

# getCommentsFromArticle,
GET {{url}}/articles/swan-prattle-now-steep-where/comments

# deleteComment,
DELETE {{url}}/articles/short/comments/666bc73e0468773871939b84
Authorization: {{token0}}
