# get all my contacts
GET {{url}}/contacts
Authorization: {{token0}}

# create a new contact
POST {{url}}/contacts
Content-Type: application/json
{
  "contact": {
    "name":"Minh Hoc Code 111",
    "email":"minhoccode111@gmail.com",
    "body":"Hey, can we collaborate?",
    "markAsRead": false
  }
}

# update contact
PUT {{url}}/contacts/6683fe3231277187ae108bfe
Authorization: {{token0}}
Content-Type: application/json
{
  "contact": {
    "markAsRead": true
  }
}

# delete a contact
DELETE {{url}}/contacts/6683fe3231277187ae108bfe
Authorization: {{token0}}
