# return index.html
GET {{url}}/index

# return "successful"
# manually type because the {{url}} === http://localhost:3000/api
GET http://localhost:3000/test

# sign up
POST {{url}}/users
Content-Type: application/json
{
  "_comment": "this is syntax of http json",
  "user": {
    "username":"asd1",
    "email":"1@gmail.com",
    "password":"Bruh0!0!"
  }
}

# sign in
POST {{url}}/users/login
Content-Type: application/json
{
  "user": {
    "email":"asd1@gmail.com",
    "password":"asd"
  }
}

# update user
PUT {{url}}/user
Authorization: {{token0}}
Content-Type: application/json
{
  "user": {
    "email": "minhhoccode111@gmail.com", 
    "username": "minhhoccode111", 
    "password": "asd", 
    "image": "https://avatars.githubusercontent.com/u/39550308",
    "bio": "I write code (sometimes)"
  }
}

# get current user
GET {{url}}/user
Authorization: {{token0}}
