# return index.html
GET {{url}}/index

# return "successful"
# manually type because the {{url}} === http://localhost:3000/api
GET http://localhost:3000/test

GET http://localhost:3000/kkk

# sign up
POST {{url}}/users
Content-Type: application/json
{
  "_comment": "this is syntax of http json",
  "user": {
    "username":"asd1",
    "email":"asd1@gmail.com",
    "password":"Bruh0!0!"
  }
}

# sign in
POST {{url}}/users/login
Content-Type: application/json
{
  "user": {
    "email":"asd1@gmail.com",
    "password":"Bruh0!0!"
  }
}

# update user, need auth
PUT {{url}}/user
Authorization: {{token0}}
Content-Type: application/json
{
  "user": {
    "email": "asd4@gmail.com", 
    "username": "asd4", 
    "password": "Bruh0!0!", 
    "image": "https://google.com",
    "bio": "I write code (sometimes)"
  }
}

# get current user, need auth
GET {{url}}/user
Authorization: {{token0}}
